

# This file was *autogenerated* from the file dilithium-III.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_256 = Integer(256); _sage_const_8 = Integer(8); _sage_const_8380417 = Integer(8380417); _sage_const_1p = RealNumber('1.'); _sage_const_1 = Integer(1); _sage_const_20 = Integer(20)
load("../framework/instance_gen.sage")

verbosity = _sage_const_2 
report_every = None

# Dilithium-III round-3 parameters
n = _sage_const_7 *_sage_const_256 
m = _sage_const_8 *_sage_const_256 
q = _sage_const_8380417 
eta = _sage_const_2 
D_s = {x : _sage_const_1p /(_sage_const_2 *eta+_sage_const_1 ) for x in range(-eta, eta+_sage_const_1 )}
D_e = D_s

_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=_sage_const_20 )
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")

inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

