

# This file was *autogenerated* from the file run_all_applications.sage
from sage.all_cmdline import *   # import sage library

print("\nFor Table 3\n")
load("exploiting_SCA_from_Bos_et_al.sage")
print("\nFor Table 4 \n")
load("exploiting_design_LAC.sage")
load("exploiting_design_ntru.sage")
load("exploiting_design_round5.sage")
print("\nFor Remark 5\n")
load("exploiting_design_ntru_prime.sage")
print("\nFor Figure 5\n")
load("exploiting_decryption_failures.sage")

