print("Generating all data (takes a while...)")
print("\nFor Table 3\n")
load("exploiting_SCA_from_Bos_et_al.sage")
print("\nFor Figure 6\n")
load("exploiting_decryption_failures.sage")
print("\nFor Table 4 \n")
load("exploiting_design_LAC.sage")
load("exploiting_design_ntru.sage")
load("exploiting_design_round5.sage")